### ISSUE TITLE
Load `config.yml` file

### ISSUE THREAD

**Issue by copelco** [caktus/ansible-collection-caktus-tech-support#3]
AC:
- [x] main function loads `config.yml`
- [x] Use argparse module to capture 1st positional argument as config file
- [x] `UptimeTest()` is instantiated for each test defined in `uptime_tests`
- [x] `python statuscake.py config.yml` prints fetch output for each test

Example yaml file:

```yaml
# file: config.yml
api_key: AAABBBCCC

uptime_tests:
 - name: Caktus Website 
   state: present
   website_url: https://www.caktusgroup.com/services/
 - name: Chippy
   state: present
   website_url: https://chippy.cloud/
```
