### ISSUE TITLE
Uptimetest: create test from yaml file

### ISSUE THREAD

**Issue by copelco** [caktus/ansible-collection-caktus-tech-support#4]
AC:
- [x] A new test is created in StatusCake when `state: present` AND a test with `name` does not exist yet

Example yaml:

```yaml
uptime_tests:
 - name: Caktus Website 
   state: present
   website_url: https://www.caktusgroup.com/services/
```
