### ISSUE TITLE
Uptimetest: update test

### ISSUE THREAD

**Issue by copelco** [caktus/ansible-collection-caktus-tech-support#5]
AC:
- [x] A `PUT` request is made to `/v1/uptime/{testid}` ([docs](https://www.statuscake.com/api/v1/#operation/update-uptime-test))
- [x] A test is updated in StatusCake when `state: present` AND a test with `name` does exist

Run 1:

```yaml
uptime_tests:
 - name: Caktus Website 
   state: present
   website_url: https://www.caktusgroup.com/services/
   basic_user: admin
   basic_pass: mypass
```

Run 2:

```yaml
uptime_tests:
 - name: Caktus Website 
   state: present
   website_url: https://www.caktusgroup.com/services/
```

After Run 2, the Caktus Website test should not have `basic_user` or `basic_path` associated with it anymore.
